---

spring:
  profiles: local    
server:
  port: 8081

---

spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/native-config

---

spring:
  profiles: cloud
  cloud:
    config:
      server:
        git:
          uri: ${vcap.services.config-repo.credentials.uri}
          username: ${vcap.services.config-repo.credentials.username}
          password: ${vcap.services.config-repo.credentials.password} 
  security:
    user:
      name: ${vcap.services.basic-auth.credentials.username}
      password: ${vcap.services.basic-auth.credentials.password}
     