---

spring:
  profiles:
    active: local
    
server:
  port: 8081
  

---

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/native-config

---

spring:
  profiles:
    active: cloud
  cloud:
    config:
      server:
        git:
          uri: ${vcap.services.config-repo.uri}
          username: ${vcap.services.config-repo.username}
          password: ${vcap.services.config-repo.password}   